// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChannelBotIssue.
const (
	NoRights ChannelBotIssue = "no_rights"
	None     ChannelBotIssue = "none"
	Removed  ChannelBotIssue = "removed"
)

// Valid indicates whether the value is a known member of the ChannelBotIssue enum.
func (e ChannelBotIssue) Valid() bool {
	switch e {
	case NoRights:
		return true
	case None:
		return true
	case Removed:
		return true
	default:
		return false
	}
}

// Defines values for ChannelChatType.
const (
	ChannelChatTypeChannel    ChannelChatType = "channel"
	ChannelChatTypeGroup      ChannelChatType = "group"
	ChannelChatTypeSupergroup ChannelChatType = "supergroup"
)

// Valid indicates whether the value is a known member of the ChannelChatType enum.
func (e ChannelChatType) Valid() bool {
	switch e {
	case ChannelChatTypeChannel:
		return true
	case ChannelChatTypeGroup:
		return true
	case ChannelChatTypeSupergroup:
		return true
	default:
		return false
	}
}

// Defines values for MySubscriptionStatus.
const (
	Active   MySubscriptionStatus = "active"
	Canceled MySubscriptionStatus = "canceled"
	Expired  MySubscriptionStatus = "expired"
)

// Valid indicates whether the value is a known member of the MySubscriptionStatus enum.
func (e MySubscriptionStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Canceled:
		return true
	case Expired:
		return true
	default:
		return false
	}
}

// Defines values for PaymentMethod.
const (
	PaymentMethodCard PaymentMethod = "card"
	PaymentMethodSbp  PaymentMethod = "sbp"
)

// Valid indicates whether the value is a known member of the PaymentMethod enum.
func (e PaymentMethod) Valid() bool {
	switch e {
	case PaymentMethodCard:
		return true
	case PaymentMethodSbp:
		return true
	default:
		return false
	}
}

// Defines values for PaymentStatusStatus.
const (
	Failed    PaymentStatusStatus = "failed"
	Pending   PaymentStatusStatus = "pending"
	Refunded  PaymentStatusStatus = "refunded"
	Succeeded PaymentStatusStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentStatusStatus enum.
func (e PaymentStatusStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Refunded:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for PayoutStatus.
const (
	Paid       PayoutStatus = "paid"
	Processing PayoutStatus = "processing"
	Rejected   PayoutStatus = "rejected"
	Requested  PayoutStatus = "requested"
)

// Valid indicates whether the value is a known member of the PayoutStatus enum.
func (e PayoutStatus) Valid() bool {
	switch e {
	case Paid:
		return true
	case Processing:
		return true
	case Rejected:
		return true
	case Requested:
		return true
	default:
		return false
	}
}

// Defines values for PayoutMethod.
const (
	PayoutMethodCard    PayoutMethod = "card"
	PayoutMethodSbp     PayoutMethod = "sbp"
	PayoutMethodUsdtTon PayoutMethod = "usdt_ton"
)

// Valid indicates whether the value is a known member of the PayoutMethod enum.
func (e PayoutMethod) Valid() bool {
	switch e {
	case PayoutMethodCard:
		return true
	case PayoutMethodSbp:
		return true
	case PayoutMethodUsdtTon:
		return true
	default:
		return false
	}
}

// Balance defines model for Balance.
type Balance struct {
	// Available Можно вывести
	Available int64 `json:"available"`

	// Currency Example: RUB
	Currency string `json:"currency"`

	// PaidOut Всего выведено
	PaidOut int64 `json:"paidOut"`

	// Pending В холде, станет доступно после окончания холда
	Pending int64 `json:"pending"`
}

// Channel defines model for Channel.
type Channel struct {
	ActiveSubscribers int64 `json:"activeSubscribers"`

	// BotIsAdmin false — бота удалили из админов, продажи остановлены
	BotIsAdmin bool `json:"botIsAdmin"`

	// BotIssue Что не так с ботом в канале. removed — бота убрали, no_rights — не хватает прав
	BotIssue ChannelBotIssue `json:"botIssue"`
	ChatType ChannelChatType `json:"chatType"`

	// ConnectedAt Когда бота последний раз добавили админом в этот канал
	ConnectedAt time.Time `json:"connectedAt"`
	Description string    `json:"description"`
	Id          int64     `json:"id"`

	// OfferUrl Ссылка на страницу оплаты, которой автор делится с аудиторией
	OfferUrl string  `json:"offerUrl"`
	Title    string  `json:"title"`
	Username *string `json:"username,omitempty"`
}

// ChannelBotIssue Что не так с ботом в канале. removed — бота убрали, no_rights — не хватает прав
type ChannelBotIssue string

// ChannelChatType defines model for Channel.ChatType.
type ChannelChatType string

// ChannelDetail defines model for ChannelDetail.
type ChannelDetail struct {
	Channel  Channel   `json:"channel"`
	Products []Product `json:"products"`
}

// ChannelUpdate defines model for ChannelUpdate.
type ChannelUpdate struct {
	Description string `json:"description"`
}

// Checkout defines model for Checkout.
type Checkout struct {
	PaymentId  openapi_types.UUID `json:"paymentId"`
	PaymentUrl string             `json:"paymentUrl"`
}

// CheckoutRequest defines model for CheckoutRequest.
type CheckoutRequest struct {
	Method PaymentMethod `json:"method"`
	PlanId int64         `json:"planId"`
}

// ConnectLink defines model for ConnectLink.
type ConnectLink struct {
	BotUsername string `json:"botUsername"`
	Url         string `json:"url"`
}

// DailyPoint defines model for DailyPoint.
type DailyPoint struct {
	Date     openapi_types.Date `json:"date"`
	Net      int64              `json:"net"`
	Payments int64              `json:"payments"`
}

// DayPayment defines model for DayPayment.
type DayPayment struct {
	Amount       int64              `json:"amount"`
	ChannelTitle string             `json:"channelTitle"`
	Id           openapi_types.UUID `json:"id"`
	Method       PaymentMethod      `json:"method"`
	Net          int64              `json:"net"`
	PaidAt       time.Time          `json:"paidAt"`
	PayerName    string             `json:"payerName"`
	PlanTitle    string             `json:"planTitle"`
}

// Error defines model for Error.
type Error struct {
	// Code Машиночитаемый код (not_found, forbidden, validation, ...)
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Me defines model for Me.
type Me struct {
	Balance Balance `json:"balance"`

	// CommissionBps Комиссия платформы для этого автора, 2000 = 20%
	CommissionBps int            `json:"commissionBps"`
	HoldHours     int            `json:"holdHours"`
	MinPayout     int64          `json:"minPayout"`
	PayoutMethods []PayoutMethod `json:"payoutMethods"`
	User          User           `json:"user"`
}

// MySubscription defines model for MySubscription.
type MySubscription struct {
	ChannelId       int64   `json:"channelId"`
	ChannelTitle    string  `json:"channelTitle"`
	ChannelUsername *string `json:"channelUsername,omitempty"`

	// ExpiresAt Отсутствует у бессрочного доступа
	ExpiresAt  *time.Time           `json:"expiresAt,omitempty"`
	Id         int64                `json:"id"`
	InviteLink *string              `json:"inviteLink,omitempty"`
	PlanTitle  string               `json:"planTitle"`
	StartedAt  time.Time            `json:"startedAt"`
	Status     MySubscriptionStatus `json:"status"`
}

// MySubscriptionStatus defines model for MySubscription.Status.
type MySubscriptionStatus string

// Offer defines model for Offer.
type Offer struct {
	// Available false — канал временно не принимает оплату
	Available   bool    `json:"available"`
	ButtonText  string  `json:"buttonText"`
	ChannelId   int64   `json:"channelId"`
	Description string  `json:"description"`
	ImageUrl    *string `json:"imageUrl,omitempty"`

	// Own true — страницу открыл владелец канала, купить у себя нельзя
	Own            bool            `json:"own"`
	PaymentMethods []PaymentMethod `json:"paymentMethods"`
	Plans          []Plan          `json:"plans"`

	// ProductId Отсутствует, если у канала нет подписок в продаже
	ProductId    *int64          `json:"productId,omitempty"`
	ProductTitle *string         `json:"productTitle,omitempty"`
	Subscription *MySubscription `json:"subscription,omitempty"`

	// Title Название канала
	Title    string  `json:"title"`
	Username *string `json:"username,omitempty"`
}

// PaymentMethod defines model for PaymentMethod.
type PaymentMethod string

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus struct {
	Amount       int64              `json:"amount"`
	ChannelId    int64              `json:"channelId"`
	ChannelTitle string             `json:"channelTitle"`
	Currency     string             `json:"currency"`
	Id           openapi_types.UUID `json:"id"`

	// InviteLink Появляется после успешной оплаты
	InviteLink *string             `json:"inviteLink,omitempty"`
	Status     PaymentStatusStatus `json:"status"`
}

// PaymentStatusStatus defines model for PaymentStatus.Status.
type PaymentStatusStatus string

// Payout defines model for Payout.
type Payout struct {
	Amount    int64     `json:"amount"`
	Comment   *string   `json:"comment,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	Currency  string    `json:"currency"`

	// Destination Замаскированные реквизиты
	Destination string       `json:"destination"`
	Id          int64        `json:"id"`
	Method      PayoutMethod `json:"method"`
	ProcessedAt *time.Time   `json:"processedAt,omitempty"`
	Status      PayoutStatus `json:"status"`
}

// PayoutStatus defines model for Payout.Status.
type PayoutStatus string

// PayoutMethod defines model for PayoutMethod.
type PayoutMethod string

// PayoutRequest defines model for PayoutRequest.
type PayoutRequest struct {
	Amount      int64        `json:"amount"`
	Destination string       `json:"destination"`
	Method      PayoutMethod `json:"method"`
}

// Plan defines model for Plan.
type Plan struct {
	ChannelId int64  `json:"channelId"`
	Currency  string `json:"currency"`
	Id        int64  `json:"id"`
	IsActive  bool   `json:"isActive"`

	// PeriodDays 0 — бессрочный доступ
	PeriodDays int   `json:"periodDays"`
	Price      int64 `json:"price"`
	ProductId  int64 `json:"productId"`

	// Title Название периода, собирается из срока
	Title string `json:"title"`
}

// PlanInput defines model for PlanInput.
type PlanInput struct {
	PeriodDays int   `json:"periodDays"`
	Price      int64 `json:"price"`
}

// PlanUpdate defines model for PlanUpdate.
type PlanUpdate struct {
	IsActive   bool  `json:"isActive"`
	PeriodDays int   `json:"periodDays"`
	Price      int64 `json:"price"`
}

// PreparedShare defines model for PreparedShare.
type PreparedShare struct {
	// PreparedMessageId Идентификатор для WebApp.shareMessage
	PreparedMessageId string `json:"preparedMessageId"`
}

// Product defines model for Product.
type Product struct {
	ActiveSubscribers int64 `json:"activeSubscribers"`

	// ButtonText Надпись на кнопке под постом
	ButtonText   string              `json:"buttonText"`
	ChannelId    int64               `json:"channelId"`
	ChannelTitle string              `json:"channelTitle"`
	Description  string              `json:"description"`
	Id           int64               `json:"id"`
	ImageId      *openapi_types.UUID `json:"imageId,omitempty"`
	ImageUrl     *string             `json:"imageUrl,omitempty"`
	IsActive     bool                `json:"isActive"`

	// PaymentMethods Пустой список — доступны все способы
	PaymentMethods []PaymentMethod `json:"paymentMethods"`
	Plans          []Plan          `json:"plans"`
	Title          string          `json:"title"`

	// Url Ссылка на страницу оплаты этой подписки
	Url string `json:"url"`
}

// ProductCreate defines model for ProductCreate.
type ProductCreate struct {
	ButtonText  *string `json:"buttonText,omitempty"`
	Description *string `json:"description,omitempty"`

	// ImageId Не передан — картинки нет
	ImageId        *openapi_types.UUID `json:"imageId,omitempty"`
	PaymentMethods *[]PaymentMethod    `json:"paymentMethods,omitempty"`

	// Plans Периоды, с которыми создаётся подписка. Сроки не повторяются
	Plans []PlanInput `json:"plans"`
	Title string      `json:"title"`
}

// ProductInput defines model for ProductInput.
type ProductInput struct {
	ButtonText  *string `json:"buttonText,omitempty"`
	Description *string `json:"description,omitempty"`

	// ImageId Не передан — картинки нет
	ImageId        *openapi_types.UUID `json:"imageId,omitempty"`
	PaymentMethods *[]PaymentMethod    `json:"paymentMethods,omitempty"`
	Title          string              `json:"title"`
}

// ProductUpdate defines model for ProductUpdate.
type ProductUpdate struct {
	ButtonText  *string `json:"buttonText,omitempty"`
	Description *string `json:"description,omitempty"`

	// ImageId Не передан — картинки нет
	ImageId        *openapi_types.UUID `json:"imageId,omitempty"`
	IsActive       bool                `json:"isActive"`
	PaymentMethods *[]PaymentMethod    `json:"paymentMethods,omitempty"`
	Title          string              `json:"title"`
}

// Stats defines model for Stats.
type Stats struct {
	ActiveSubscribers  int64        `json:"activeSubscribers"`
	ChurnedSubscribers int64        `json:"churnedSubscribers"`
	Currency           string       `json:"currency"`
	Daily              []DailyPoint `json:"daily"`
	Days               int          `json:"days"`

	// GrossRevenue Сколько заплатили подписчики
	GrossRevenue int64 `json:"grossRevenue"`

	// NetRevenue Доход автора после комиссии
	NetRevenue     int64 `json:"netRevenue"`
	NewSubscribers int64 `json:"newSubscribers"`
	PayingUsers    int64 `json:"payingUsers"`
	PaymentsCount  int64 `json:"paymentsCount"`
}

// User defines model for User.
type User struct {
	FirstName string  `json:"firstName"`
	Id        int64   `json:"id"`
	LastName  string  `json:"lastName"`
	PhotoUrl  *string `json:"photoUrl,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// ChannelId defines model for ChannelId.
type ChannelId = int64

// ProductId defines model for ProductId.
type ProductId = int64

// GetStatsParams defines parameters for GetStats.
type GetStatsParams struct {
	Days *int `form:"days,omitempty" json:"days,omitempty"`

	// ChannelId Только один канал автора
	ChannelId *int64 `form:"channelId,omitempty" json:"channelId,omitempty"`
}

// ListDayPaymentsParams defines parameters for ListDayPayments.
type ListDayPaymentsParams struct {
	// Date День. Без него отдаются последние оплаты
	Date *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`

	// ChannelId Только один канал автора
	ChannelId *int64 `form:"channelId,omitempty" json:"channelId,omitempty"`
	Limit     *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateChannelJSONRequestBody defines body for UpdateChannel for application/json ContentType.
type UpdateChannelJSONRequestBody = ChannelUpdate

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = ProductCreate

// CreateCheckoutJSONRequestBody defines body for CreateCheckout for application/json ContentType.
type CreateCheckoutJSONRequestBody = CheckoutRequest

// RequestPayoutJSONRequestBody defines body for RequestPayout for application/json ContentType.
type RequestPayoutJSONRequestBody = PayoutRequest

// UpdatePlanJSONRequestBody defines body for UpdatePlan for application/json ContentType.
type UpdatePlanJSONRequestBody = PlanUpdate

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = ProductUpdate

// CreatePlanJSONRequestBody defines body for CreatePlan for application/json ContentType.
type CreatePlanJSONRequestBody = PlanInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListChannels Каналы, где текущий пользователь — владелец
	// (GET /channels)
	ListChannels(w http.ResponseWriter, r *http.Request)
	// GetConnectLink Ссылка, по которой автор добавляет бота админом в свой канал
	// (GET /channels/connect)
	GetConnectLink(w http.ResponseWriter, r *http.Request)
	// DeleteChannel Удалить канал из Pitly. Продажи останавливаются, бот выходит из канала
	// (DELETE /channels/{channelId})
	DeleteChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// GetChannel Канал с подписками (только для владельца)
	// (GET /channels/{channelId})
	GetChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// UpdateChannel Обновить описание канала на странице оплаты
	// (PATCH /channels/{channelId})
	UpdateChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// CreateProduct Создать подписку в канале вместе с периодами
	// (POST /channels/{channelId}/products)
	CreateProduct(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// CreateCheckout Создать платёж и получить ссылку на оплату
	// (POST /checkout)
	CreateCheckout(w http.ResponseWriter, r *http.Request)
	// GetMe Текущий пользователь, баланс и настройки платформы
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// GetOffer Страница оплаты канала для подписчика — первая подписка, которая в продаже
	// (GET /offers/{channelId})
	GetOffer(w http.ResponseWriter, r *http.Request, channelId ChannelId)
	// GetPayment Статус платежа (подписчик опрашивает после возврата со страницы оплаты)
	// (GET /payments/{paymentId})
	GetPayment(w http.ResponseWriter, r *http.Request, paymentId openapi_types.UUID)
	// ListPayouts История выводов
	// (GET /payouts)
	ListPayouts(w http.ResponseWriter, r *http.Request)
	// RequestPayout Запросить вывод доступного баланса
	// (POST /payouts)
	RequestPayout(w http.ResponseWriter, r *http.Request)
	// UpdatePlan Изменить период
	// (PUT /plans/{planId})
	UpdatePlan(w http.ResponseWriter, r *http.Request, planId int64)
	// DeleteProduct Удалить подписку. Кто уже оплатил, сохраняет доступ до конца срока
	// (DELETE /products/{productId})
	DeleteProduct(w http.ResponseWriter, r *http.Request, productId ProductId)
	// GetProduct Подписка с периодами (только для владельца)
	// (GET /products/{productId})
	GetProduct(w http.ResponseWriter, r *http.Request, productId ProductId)
	// UpdateProduct Изменить название, описание, оформление и способы оплаты
	// (PUT /products/{productId})
	UpdateProduct(w http.ResponseWriter, r *http.Request, productId ProductId)
	// GetProductOffer Страница оплаты конкретной подписки для подписчика
	// (GET /products/{productId}/offer)
	GetProductOffer(w http.ResponseWriter, r *http.Request, productId ProductId)
	// CreatePlan Добавить период подписки
	// (POST /products/{productId}/plans)
	CreatePlan(w http.ResponseWriter, r *http.Request, productId ProductId)
	// ShareProduct Подготовить пост подписки, который автор отправит в чат или канал
	// (POST /products/{productId}/share)
	ShareProduct(w http.ResponseWriter, r *http.Request, productId ProductId)
	// GetStats Статистика автора
	// (GET /stats)
	GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams)
	// ListDayPayments Успешные оплаты автора — за один день или последние
	// (GET /stats/payments)
	ListDayPayments(w http.ResponseWriter, r *http.Request, params ListDayPaymentsParams)
	// ListMySubscriptions Подписки текущего пользователя как подписчика
	// (GET /subscriptions)
	ListMySubscriptions(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListChannels Каналы, где текущий пользователь — владелец
// (GET /channels)
func (_ Unimplemented) ListChannels(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetConnectLink Ссылка, по которой автор добавляет бота админом в свой канал
// (GET /channels/connect)
func (_ Unimplemented) GetConnectLink(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteChannel Удалить канал из Pitly. Продажи останавливаются, бот выходит из канала
// (DELETE /channels/{channelId})
func (_ Unimplemented) DeleteChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetChannel Канал с подписками (только для владельца)
// (GET /channels/{channelId})
func (_ Unimplemented) GetChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateChannel Обновить описание канала на странице оплаты
// (PATCH /channels/{channelId})
func (_ Unimplemented) UpdateChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateProduct Создать подписку в канале вместе с периодами
// (POST /channels/{channelId}/products)
func (_ Unimplemented) CreateProduct(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateCheckout Создать платёж и получить ссылку на оплату
// (POST /checkout)
func (_ Unimplemented) CreateCheckout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Текущий пользователь, баланс и настройки платформы
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetOffer Страница оплаты канала для подписчика — первая подписка, которая в продаже
// (GET /offers/{channelId})
func (_ Unimplemented) GetOffer(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPayment Статус платежа (подписчик опрашивает после возврата со страницы оплаты)
// (GET /payments/{paymentId})
func (_ Unimplemented) GetPayment(w http.ResponseWriter, r *http.Request, paymentId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListPayouts История выводов
// (GET /payouts)
func (_ Unimplemented) ListPayouts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RequestPayout Запросить вывод доступного баланса
// (POST /payouts)
func (_ Unimplemented) RequestPayout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdatePlan Изменить период
// (PUT /plans/{planId})
func (_ Unimplemented) UpdatePlan(w http.ResponseWriter, r *http.Request, planId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteProduct Удалить подписку. Кто уже оплатил, сохраняет доступ до конца срока
// (DELETE /products/{productId})
func (_ Unimplemented) DeleteProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetProduct Подписка с периодами (только для владельца)
// (GET /products/{productId})
func (_ Unimplemented) GetProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateProduct Изменить название, описание, оформление и способы оплаты
// (PUT /products/{productId})
func (_ Unimplemented) UpdateProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetProductOffer Страница оплаты конкретной подписки для подписчика
// (GET /products/{productId}/offer)
func (_ Unimplemented) GetProductOffer(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreatePlan Добавить период подписки
// (POST /products/{productId}/plans)
func (_ Unimplemented) CreatePlan(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ShareProduct Подготовить пост подписки, который автор отправит в чат или канал
// (POST /products/{productId}/share)
func (_ Unimplemented) ShareProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetStats Статистика автора
// (GET /stats)
func (_ Unimplemented) GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListDayPayments Успешные оплаты автора — за один день или последние
// (GET /stats/payments)
func (_ Unimplemented) ListDayPayments(w http.ResponseWriter, r *http.Request, params ListDayPaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListMySubscriptions Подписки текущего пользователя как подписчика
// (GET /subscriptions)
func (_ Unimplemented) ListMySubscriptions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListChannels operation middleware
func (siw *ServerInterfaceWrapper) ListChannels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChannels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConnectLink operation middleware
func (siw *ServerInterfaceWrapper) GetConnectLink(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConnectLink(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChannel operation middleware
func (siw *ServerInterfaceWrapper) DeleteChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", chi.URLParam(r, "channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChannel operation middleware
func (siw *ServerInterfaceWrapper) GetChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", chi.URLParam(r, "channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateChannel operation middleware
func (siw *ServerInterfaceWrapper) UpdateChannel(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", chi.URLParam(r, "channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateChannel(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", chi.URLParam(r, "channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProduct(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCheckout operation middleware
func (siw *ServerInterfaceWrapper) CreateCheckout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCheckout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOffer operation middleware
func (siw *ServerInterfaceWrapper) GetOffer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "channelId" -------------
	var channelId ChannelId

	err = runtime.BindStyledParameterWithOptions("simple", "channelId", chi.URLParam(r, "channelId"), &channelId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOffer(w, r, channelId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPayment operation middleware
func (siw *ServerInterfaceWrapper) GetPayment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "paymentId" -------------
	var paymentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "paymentId", chi.URLParam(r, "paymentId"), &paymentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paymentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPayment(w, r, paymentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPayouts operation middleware
func (siw *ServerInterfaceWrapper) ListPayouts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPayouts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPayout operation middleware
func (siw *ServerInterfaceWrapper) RequestPayout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPayout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePlan operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "planId" -------------
	var planId int64

	err = runtime.BindStyledParameterWithOptions("simple", "planId", chi.URLParam(r, "planId"), &planId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "planId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePlan(w, r, planId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProduct operation middleware
func (siw *ServerInterfaceWrapper) DeleteProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProductOffer operation middleware
func (siw *ServerInterfaceWrapper) GetProductOffer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProductOffer(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlan operation middleware
func (siw *ServerInterfaceWrapper) CreatePlan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlan(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ShareProduct operation middleware
func (siw *ServerInterfaceWrapper) ShareProduct(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ShareProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatsParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "days", r.URL.Query(), &params.Days, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channelId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelId", r.URL.Query(), &params.ChannelId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channelId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDayPayments operation middleware
func (siw *ServerInterfaceWrapper) ListDayPayments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDayPaymentsParams

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "date", r.URL.Query(), &params.Date, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "channelId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "channelId", r.URL.Query(), &params.ChannelId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "channelId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "channelId", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDayPayments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMySubscriptions operation middleware
func (siw *ServerInterfaceWrapper) ListMySubscriptions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMySubscriptions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/channels", wrapper.ListChannels)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/channels/connect", wrapper.GetConnectLink)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/channels/{channelId}", wrapper.DeleteChannel)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/channels/{channelId}", wrapper.GetChannel)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/channels/{channelId}", wrapper.UpdateChannel)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/channels/{channelId}/products", wrapper.CreateProduct)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/products/{productId}", wrapper.DeleteProduct)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/products/{productId}", wrapper.GetProduct)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/products/{productId}", wrapper.UpdateProduct)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/products/{productId}/plans", wrapper.CreatePlan)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/products/{productId}/share", wrapper.ShareProduct)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/products/{productId}/offer", wrapper.GetProductOffer)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/plans/{planId}", wrapper.UpdatePlan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/offers/{channelId}", wrapper.GetOffer)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/checkout", wrapper.CreateCheckout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/payments/{paymentId}", wrapper.GetPayment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/subscriptions", wrapper.ListMySubscriptions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats", wrapper.GetStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stats/payments", wrapper.ListDayPayments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/payouts", wrapper.ListPayouts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/payouts", wrapper.RequestPayout)
	})

	return r
}

type ErrorJSONResponse Error

type ListChannelsRequestObject struct {
}

type ListChannelsResponseObject interface {
	VisitListChannelsResponse(w http.ResponseWriter) error
}

type ListChannels200JSONResponse []Channel

func (response ListChannels200JSONResponse) VisitListChannelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListChannelsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListChannelsdefaultJSONResponse) VisitListChannelsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetConnectLinkRequestObject struct {
}

type GetConnectLinkResponseObject interface {
	VisitGetConnectLinkResponse(w http.ResponseWriter) error
}

type GetConnectLink200JSONResponse ConnectLink

func (response GetConnectLink200JSONResponse) VisitGetConnectLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetConnectLinkdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetConnectLinkdefaultJSONResponse) VisitGetConnectLinkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteChannelRequestObject struct {
	ChannelId ChannelId `json:"channelId"`
}

type DeleteChannelResponseObject interface {
	VisitDeleteChannelResponse(w http.ResponseWriter) error
}

type DeleteChannel204Response struct {
}

func (response DeleteChannel204Response) VisitDeleteChannelResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteChanneldefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteChanneldefaultJSONResponse) VisitDeleteChannelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetChannelRequestObject struct {
	ChannelId ChannelId `json:"channelId"`
}

type GetChannelResponseObject interface {
	VisitGetChannelResponse(w http.ResponseWriter) error
}

type GetChannel200JSONResponse ChannelDetail

func (response GetChannel200JSONResponse) VisitGetChannelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetChanneldefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetChanneldefaultJSONResponse) VisitGetChannelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateChannelRequestObject struct {
	ChannelId ChannelId `json:"channelId"`
	Body      *UpdateChannelJSONRequestBody
}

type UpdateChannelResponseObject interface {
	VisitUpdateChannelResponse(w http.ResponseWriter) error
}

type UpdateChannel200JSONResponse Channel

func (response UpdateChannel200JSONResponse) VisitUpdateChannelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateChanneldefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateChanneldefaultJSONResponse) VisitUpdateChannelResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProductRequestObject struct {
	ChannelId ChannelId `json:"channelId"`
	Body      *CreateProductJSONRequestBody
}

type CreateProductResponseObject interface {
	VisitCreateProductResponse(w http.ResponseWriter) error
}

type CreateProduct201JSONResponse Product

func (response CreateProduct201JSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProductdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateProductdefaultJSONResponse) VisitCreateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckoutRequestObject struct {
	Body *CreateCheckoutJSONRequestBody
}

type CreateCheckoutResponseObject interface {
	VisitCreateCheckoutResponse(w http.ResponseWriter) error
}

type CreateCheckout201JSONResponse Checkout

func (response CreateCheckout201JSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCheckoutdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreateCheckoutdefaultJSONResponse) VisitCreateCheckoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetMedefaultJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetOfferRequestObject struct {
	ChannelId ChannelId `json:"channelId"`
}

type GetOfferResponseObject interface {
	VisitGetOfferResponse(w http.ResponseWriter) error
}

type GetOffer200JSONResponse Offer

func (response GetOffer200JSONResponse) VisitGetOfferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOfferdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetOfferdefaultJSONResponse) VisitGetOfferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetPaymentRequestObject struct {
	PaymentId openapi_types.UUID `json:"paymentId"`
}

type GetPaymentResponseObject interface {
	VisitGetPaymentResponse(w http.ResponseWriter) error
}

type GetPayment200JSONResponse PaymentStatus

func (response GetPayment200JSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPaymentdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetPaymentdefaultJSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListPayoutsRequestObject struct {
}

type ListPayoutsResponseObject interface {
	VisitListPayoutsResponse(w http.ResponseWriter) error
}

type ListPayouts200JSONResponse []Payout

func (response ListPayouts200JSONResponse) VisitListPayoutsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPayoutsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListPayoutsdefaultJSONResponse) VisitListPayoutsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type RequestPayoutRequestObject struct {
	Body *RequestPayoutJSONRequestBody
}

type RequestPayoutResponseObject interface {
	VisitRequestPayoutResponse(w http.ResponseWriter) error
}

type RequestPayout201JSONResponse Payout

func (response RequestPayout201JSONResponse) VisitRequestPayoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type RequestPayoutdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response RequestPayoutdefaultJSONResponse) VisitRequestPayoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePlanRequestObject struct {
	PlanId int64 `json:"planId"`
	Body   *UpdatePlanJSONRequestBody
}

type UpdatePlanResponseObject interface {
	VisitUpdatePlanResponse(w http.ResponseWriter) error
}

type UpdatePlan200JSONResponse Plan

func (response UpdatePlan200JSONResponse) VisitUpdatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdatePlandefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdatePlandefaultJSONResponse) VisitUpdatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteProductRequestObject struct {
	ProductId ProductId `json:"productId"`
}

type DeleteProductResponseObject interface {
	VisitDeleteProductResponse(w http.ResponseWriter) error
}

type DeleteProduct204Response struct {
}

func (response DeleteProduct204Response) VisitDeleteProductResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteProductdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response DeleteProductdefaultJSONResponse) VisitDeleteProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProductRequestObject struct {
	ProductId ProductId `json:"productId"`
}

type GetProductResponseObject interface {
	VisitGetProductResponse(w http.ResponseWriter) error
}

type GetProduct200JSONResponse Product

func (response GetProduct200JSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProductdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetProductdefaultJSONResponse) VisitGetProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProductRequestObject struct {
	ProductId ProductId `json:"productId"`
	Body      *UpdateProductJSONRequestBody
}

type UpdateProductResponseObject interface {
	VisitUpdateProductResponse(w http.ResponseWriter) error
}

type UpdateProduct200JSONResponse Product

func (response UpdateProduct200JSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateProductdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response UpdateProductdefaultJSONResponse) VisitUpdateProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetProductOfferRequestObject struct {
	ProductId ProductId `json:"productId"`
}

type GetProductOfferResponseObject interface {
	VisitGetProductOfferResponse(w http.ResponseWriter) error
}

type GetProductOffer200JSONResponse Offer

func (response GetProductOffer200JSONResponse) VisitGetProductOfferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProductOfferdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetProductOfferdefaultJSONResponse) VisitGetProductOfferResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlanRequestObject struct {
	ProductId ProductId `json:"productId"`
	Body      *CreatePlanJSONRequestBody
}

type CreatePlanResponseObject interface {
	VisitCreatePlanResponse(w http.ResponseWriter) error
}

type CreatePlan201JSONResponse Plan

func (response CreatePlan201JSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlandefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CreatePlandefaultJSONResponse) VisitCreatePlanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ShareProductRequestObject struct {
	ProductId ProductId `json:"productId"`
}

type ShareProductResponseObject interface {
	VisitShareProductResponse(w http.ResponseWriter) error
}

type ShareProduct200JSONResponse PreparedShare

func (response ShareProduct200JSONResponse) VisitShareProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ShareProductdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ShareProductdefaultJSONResponse) VisitShareProductResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatsRequestObject struct {
	Params GetStatsParams
}

type GetStatsResponseObject interface {
	VisitGetStatsResponse(w http.ResponseWriter) error
}

type GetStats200JSONResponse Stats

func (response GetStats200JSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetStatsdefaultJSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListDayPaymentsRequestObject struct {
	Params ListDayPaymentsParams
}

type ListDayPaymentsResponseObject interface {
	VisitListDayPaymentsResponse(w http.ResponseWriter) error
}

type ListDayPayments200JSONResponse []DayPayment

func (response ListDayPayments200JSONResponse) VisitListDayPaymentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDayPaymentsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListDayPaymentsdefaultJSONResponse) VisitListDayPaymentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListMySubscriptionsRequestObject struct {
}

type ListMySubscriptionsResponseObject interface {
	VisitListMySubscriptionsResponse(w http.ResponseWriter) error
}

type ListMySubscriptions200JSONResponse []MySubscription

func (response ListMySubscriptions200JSONResponse) VisitListMySubscriptionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMySubscriptionsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListMySubscriptionsdefaultJSONResponse) VisitListMySubscriptionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListChannels Каналы, где текущий пользователь — владелец
	// (GET /channels)
	ListChannels(ctx context.Context, request ListChannelsRequestObject) (ListChannelsResponseObject, error)
	// GetConnectLink Ссылка, по которой автор добавляет бота админом в свой канал
	// (GET /channels/connect)
	GetConnectLink(ctx context.Context, request GetConnectLinkRequestObject) (GetConnectLinkResponseObject, error)
	// DeleteChannel Удалить канал из Pitly. Продажи останавливаются, бот выходит из канала
	// (DELETE /channels/{channelId})
	DeleteChannel(ctx context.Context, request DeleteChannelRequestObject) (DeleteChannelResponseObject, error)
	// GetChannel Канал с подписками (только для владельца)
	// (GET /channels/{channelId})
	GetChannel(ctx context.Context, request GetChannelRequestObject) (GetChannelResponseObject, error)
	// UpdateChannel Обновить описание канала на странице оплаты
	// (PATCH /channels/{channelId})
	UpdateChannel(ctx context.Context, request UpdateChannelRequestObject) (UpdateChannelResponseObject, error)
	// CreateProduct Создать подписку в канале вместе с периодами
	// (POST /channels/{channelId}/products)
	CreateProduct(ctx context.Context, request CreateProductRequestObject) (CreateProductResponseObject, error)
	// CreateCheckout Создать платёж и получить ссылку на оплату
	// (POST /checkout)
	CreateCheckout(ctx context.Context, request CreateCheckoutRequestObject) (CreateCheckoutResponseObject, error)
	// GetMe Текущий пользователь, баланс и настройки платформы
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// GetOffer Страница оплаты канала для подписчика — первая подписка, которая в продаже
	// (GET /offers/{channelId})
	GetOffer(ctx context.Context, request GetOfferRequestObject) (GetOfferResponseObject, error)
	// GetPayment Статус платежа (подписчик опрашивает после возврата со страницы оплаты)
	// (GET /payments/{paymentId})
	GetPayment(ctx context.Context, request GetPaymentRequestObject) (GetPaymentResponseObject, error)
	// ListPayouts История выводов
	// (GET /payouts)
	ListPayouts(ctx context.Context, request ListPayoutsRequestObject) (ListPayoutsResponseObject, error)
	// RequestPayout Запросить вывод доступного баланса
	// (POST /payouts)
	RequestPayout(ctx context.Context, request RequestPayoutRequestObject) (RequestPayoutResponseObject, error)
	// UpdatePlan Изменить период
	// (PUT /plans/{planId})
	UpdatePlan(ctx context.Context, request UpdatePlanRequestObject) (UpdatePlanResponseObject, error)
	// DeleteProduct Удалить подписку. Кто уже оплатил, сохраняет доступ до конца срока
	// (DELETE /products/{productId})
	DeleteProduct(ctx context.Context, request DeleteProductRequestObject) (DeleteProductResponseObject, error)
	// GetProduct Подписка с периодами (только для владельца)
	// (GET /products/{productId})
	GetProduct(ctx context.Context, request GetProductRequestObject) (GetProductResponseObject, error)
	// UpdateProduct Изменить название, описание, оформление и способы оплаты
	// (PUT /products/{productId})
	UpdateProduct(ctx context.Context, request UpdateProductRequestObject) (UpdateProductResponseObject, error)
	// GetProductOffer Страница оплаты конкретной подписки для подписчика
	// (GET /products/{productId}/offer)
	GetProductOffer(ctx context.Context, request GetProductOfferRequestObject) (GetProductOfferResponseObject, error)
	// CreatePlan Добавить период подписки
	// (POST /products/{productId}/plans)
	CreatePlan(ctx context.Context, request CreatePlanRequestObject) (CreatePlanResponseObject, error)
	// ShareProduct Подготовить пост подписки, который автор отправит в чат или канал
	// (POST /products/{productId}/share)
	ShareProduct(ctx context.Context, request ShareProductRequestObject) (ShareProductResponseObject, error)
	// GetStats Статистика автора
	// (GET /stats)
	GetStats(ctx context.Context, request GetStatsRequestObject) (GetStatsResponseObject, error)
	// ListDayPayments Успешные оплаты автора — за один день или последние
	// (GET /stats/payments)
	ListDayPayments(ctx context.Context, request ListDayPaymentsRequestObject) (ListDayPaymentsResponseObject, error)
	// ListMySubscriptions Подписки текущего пользователя как подписчика
	// (GET /subscriptions)
	ListMySubscriptions(ctx context.Context, request ListMySubscriptionsRequestObject) (ListMySubscriptionsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListChannels operation middleware
func (sh *strictHandler) ListChannels(w http.ResponseWriter, r *http.Request) {
	var request ListChannelsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListChannels(ctx, request.(ListChannelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListChannels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListChannelsResponseObject); ok {
		if err := validResponse.VisitListChannelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConnectLink operation middleware
func (sh *strictHandler) GetConnectLink(w http.ResponseWriter, r *http.Request) {
	var request GetConnectLinkRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConnectLink(ctx, request.(GetConnectLinkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConnectLink")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConnectLinkResponseObject); ok {
		if err := validResponse.VisitGetConnectLinkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteChannel operation middleware
func (sh *strictHandler) DeleteChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	var request DeleteChannelRequestObject

	request.ChannelId = channelId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteChannel(ctx, request.(DeleteChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteChannel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteChannelResponseObject); ok {
		if err := validResponse.VisitDeleteChannelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChannel operation middleware
func (sh *strictHandler) GetChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	var request GetChannelRequestObject

	request.ChannelId = channelId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetChannel(ctx, request.(GetChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChannel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChannelResponseObject); ok {
		if err := validResponse.VisitGetChannelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateChannel operation middleware
func (sh *strictHandler) UpdateChannel(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	var request UpdateChannelRequestObject

	request.ChannelId = channelId

	var body UpdateChannelJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateChannel(ctx, request.(UpdateChannelRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateChannel")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateChannelResponseObject); ok {
		if err := validResponse.VisitUpdateChannelResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProduct operation middleware
func (sh *strictHandler) CreateProduct(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	var request CreateProductRequestObject

	request.ChannelId = channelId

	var body CreateProductJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProduct(ctx, request.(CreateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProductResponseObject); ok {
		if err := validResponse.VisitCreateProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCheckout operation middleware
func (sh *strictHandler) CreateCheckout(w http.ResponseWriter, r *http.Request) {
	var request CreateCheckoutRequestObject

	var body CreateCheckoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCheckout(ctx, request.(CreateCheckoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCheckout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCheckoutResponseObject); ok {
		if err := validResponse.VisitCreateCheckoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOffer operation middleware
func (sh *strictHandler) GetOffer(w http.ResponseWriter, r *http.Request, channelId ChannelId) {
	var request GetOfferRequestObject

	request.ChannelId = channelId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOffer(ctx, request.(GetOfferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOffer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOfferResponseObject); ok {
		if err := validResponse.VisitGetOfferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPayment operation middleware
func (sh *strictHandler) GetPayment(w http.ResponseWriter, r *http.Request, paymentId openapi_types.UUID) {
	var request GetPaymentRequestObject

	request.PaymentId = paymentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPayment(ctx, request.(GetPaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPaymentResponseObject); ok {
		if err := validResponse.VisitGetPaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPayouts operation middleware
func (sh *strictHandler) ListPayouts(w http.ResponseWriter, r *http.Request) {
	var request ListPayoutsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPayouts(ctx, request.(ListPayoutsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPayouts")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPayoutsResponseObject); ok {
		if err := validResponse.VisitListPayoutsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestPayout operation middleware
func (sh *strictHandler) RequestPayout(w http.ResponseWriter, r *http.Request) {
	var request RequestPayoutRequestObject

	var body RequestPayoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestPayout(ctx, request.(RequestPayoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestPayout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestPayoutResponseObject); ok {
		if err := validResponse.VisitRequestPayoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePlan operation middleware
func (sh *strictHandler) UpdatePlan(w http.ResponseWriter, r *http.Request, planId int64) {
	var request UpdatePlanRequestObject

	request.PlanId = planId

	var body UpdatePlanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePlan(ctx, request.(UpdatePlanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePlan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdatePlanResponseObject); ok {
		if err := validResponse.VisitUpdatePlanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteProduct operation middleware
func (sh *strictHandler) DeleteProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	var request DeleteProductRequestObject

	request.ProductId = productId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteProduct(ctx, request.(DeleteProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteProductResponseObject); ok {
		if err := validResponse.VisitDeleteProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProduct operation middleware
func (sh *strictHandler) GetProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	var request GetProductRequestObject

	request.ProductId = productId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProduct(ctx, request.(GetProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProductResponseObject); ok {
		if err := validResponse.VisitGetProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateProduct operation middleware
func (sh *strictHandler) UpdateProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	var request UpdateProductRequestObject

	request.ProductId = productId

	var body UpdateProductJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateProduct(ctx, request.(UpdateProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateProductResponseObject); ok {
		if err := validResponse.VisitUpdateProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProductOffer operation middleware
func (sh *strictHandler) GetProductOffer(w http.ResponseWriter, r *http.Request, productId ProductId) {
	var request GetProductOfferRequestObject

	request.ProductId = productId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProductOffer(ctx, request.(GetProductOfferRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProductOffer")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProductOfferResponseObject); ok {
		if err := validResponse.VisitGetProductOfferResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePlan operation middleware
func (sh *strictHandler) CreatePlan(w http.ResponseWriter, r *http.Request, productId ProductId) {
	var request CreatePlanRequestObject

	request.ProductId = productId

	var body CreatePlanJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlan(ctx, request.(CreatePlanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePlanResponseObject); ok {
		if err := validResponse.VisitCreatePlanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ShareProduct operation middleware
func (sh *strictHandler) ShareProduct(w http.ResponseWriter, r *http.Request, productId ProductId) {
	var request ShareProductRequestObject

	request.ProductId = productId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ShareProduct(ctx, request.(ShareProductRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ShareProduct")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ShareProductResponseObject); ok {
		if err := validResponse.VisitShareProductResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStats operation middleware
func (sh *strictHandler) GetStats(w http.ResponseWriter, r *http.Request, params GetStatsParams) {
	var request GetStatsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStats(ctx, request.(GetStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatsResponseObject); ok {
		if err := validResponse.VisitGetStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDayPayments operation middleware
func (sh *strictHandler) ListDayPayments(w http.ResponseWriter, r *http.Request, params ListDayPaymentsParams) {
	var request ListDayPaymentsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDayPayments(ctx, request.(ListDayPaymentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDayPayments")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDayPaymentsResponseObject); ok {
		if err := validResponse.VisitListDayPaymentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMySubscriptions operation middleware
func (sh *strictHandler) ListMySubscriptions(w http.ResponseWriter, r *http.Request) {
	var request ListMySubscriptionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMySubscriptions(ctx, request.(ListMySubscriptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMySubscriptions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMySubscriptionsResponseObject); ok {
		if err := validResponse.VisitListMySubscriptionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
