// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package store

import (
	"context"
	"time"
)

const getChannel = `-- name: GetChannel :one
SELECT id, owner_id, chat_id, chat_type, title, username, description, bot_is_admin, invite_link, created_at, updated_at, bot_issue, deleted_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ChatID,
		&i.ChatType,
		&i.Title,
		&i.Username,
		&i.Description,
		&i.BotIsAdmin,
		&i.InviteLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BotIssue,
		&i.DeletedAt,
	)
	return i, err
}

const getChannelByChatID = `-- name: GetChannelByChatID :one
SELECT id, owner_id, chat_id, chat_type, title, username, description, bot_is_admin, invite_link, created_at, updated_at, bot_issue, deleted_at FROM channels WHERE chat_id = $1
`

func (q *Queries) GetChannelByChatID(ctx context.Context, chatID int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByChatID, chatID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ChatID,
		&i.ChatType,
		&i.Title,
		&i.Username,
		&i.Description,
		&i.BotIsAdmin,
		&i.InviteLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BotIssue,
		&i.DeletedAt,
	)
	return i, err
}

const listChannelsByOwner = `-- name: ListChannelsByOwner :many
SELECT
    c.id, c.owner_id, c.chat_id, c.chat_type, c.title, c.username, c.description, c.bot_is_admin, c.invite_link, c.created_at, c.updated_at, c.bot_issue, c.deleted_at,
    (SELECT count(*) FROM subscriptions s WHERE s.channel_id = c.id AND s.status = 'active')::BIGINT AS active_subscribers
FROM channels c
WHERE c.owner_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at DESC
`

type ListChannelsByOwnerRow struct {
	ID                int64
	OwnerID           int64
	ChatID            int64
	ChatType          string
	Title             string
	Username          *string
	Description       string
	BotIsAdmin        bool
	InviteLink        *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	BotIssue          string
	DeletedAt         *time.Time
	ActiveSubscribers int64
}

func (q *Queries) ListChannelsByOwner(ctx context.Context, ownerID int64) ([]ListChannelsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listChannelsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsByOwnerRow
	for rows.Next() {
		var i ListChannelsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.ChatID,
			&i.ChatType,
			&i.Title,
			&i.Username,
			&i.Description,
			&i.BotIsAdmin,
			&i.InviteLink,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BotIssue,
			&i.DeletedAt,
			&i.ActiveSubscribers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelBotState = `-- name: SetChannelBotState :exec
UPDATE channels SET bot_is_admin = ($1::TEXT = ''), bot_issue = $1::TEXT WHERE chat_id = $2
`

type SetChannelBotStateParams struct {
	BotIssue string
	ChatID   int64
}

// Продавать можно только когда бот админ со всеми нужными правами.
func (q *Queries) SetChannelBotState(ctx context.Context, arg SetChannelBotStateParams) error {
	_, err := q.db.Exec(ctx, setChannelBotState, arg.BotIssue, arg.ChatID)
	return err
}

const setChannelInviteLink = `-- name: SetChannelInviteLink :exec
UPDATE channels SET invite_link = $2 WHERE id = $1
`

type SetChannelInviteLinkParams struct {
	ID         int64
	InviteLink *string
}

func (q *Queries) SetChannelInviteLink(ctx context.Context, arg SetChannelInviteLinkParams) error {
	_, err := q.db.Exec(ctx, setChannelInviteLink, arg.ID, arg.InviteLink)
	return err
}

const softDeleteChannel = `-- name: SoftDeleteChannel :exec
UPDATE channels SET deleted_at = now(), bot_is_admin = FALSE, invite_link = NULL WHERE id = $1
`

// Канал пропадает из приложения, продажи останавливаются. История оплат остаётся.
func (q *Queries) SoftDeleteChannel(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteChannel, id)
	return err
}

const updateChannelDescription = `-- name: UpdateChannelDescription :one
UPDATE channels SET description = $2
WHERE id = $1
RETURNING id, owner_id, chat_id, chat_type, title, username, description, bot_is_admin, invite_link, created_at, updated_at, bot_issue, deleted_at
`

type UpdateChannelDescriptionParams struct {
	ID          int64
	Description string
}

func (q *Queries) UpdateChannelDescription(ctx context.Context, arg UpdateChannelDescriptionParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannelDescription, arg.ID, arg.Description)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ChatID,
		&i.ChatType,
		&i.Title,
		&i.Username,
		&i.Description,
		&i.BotIsAdmin,
		&i.InviteLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BotIssue,
		&i.DeletedAt,
	)
	return i, err
}

const upsertChannel = `-- name: UpsertChannel :one
INSERT INTO channels (owner_id, chat_id, chat_type, title, username, bot_is_admin)
VALUES ($1, $2, $3, $4, $5, TRUE)
ON CONFLICT (chat_id) DO UPDATE SET
    owner_id     = EXCLUDED.owner_id,
    chat_type    = EXCLUDED.chat_type,
    title        = EXCLUDED.title,
    username     = EXCLUDED.username,
    bot_is_admin = TRUE,
    bot_issue    = '',
    deleted_at   = NULL,
    updated_at   = now()
RETURNING id, owner_id, chat_id, chat_type, title, username, description, bot_is_admin, invite_link, created_at, updated_at, bot_issue, deleted_at
`

type UpsertChannelParams struct {
	OwnerID  int64
	ChatID   int64
	ChatType string
	Title    string
	Username *string
}

// Бот добавлен админом в канал. Если канал уже был — обновляем данные и владельца.
func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, upsertChannel,
		arg.OwnerID,
		arg.ChatID,
		arg.ChatType,
		arg.Title,
		arg.Username,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ChatID,
		&i.ChatType,
		&i.Title,
		&i.Username,
		&i.Description,
		&i.BotIsAdmin,
		&i.InviteLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BotIssue,
		&i.DeletedAt,
	)
	return i, err
}
