// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countImagesByOwnerSince = `-- name: CountImagesByOwnerSince :one
SELECT count(*)::BIGINT FROM images WHERE owner_id = $1 AND created_at > $2
`

type CountImagesByOwnerSinceParams struct {
	OwnerID   int64
	CreatedAt time.Time
}

func (q *Queries) CountImagesByOwnerSince(ctx context.Context, arg CountImagesByOwnerSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImagesByOwnerSince, arg.OwnerID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createImage = `-- name: CreateImage :one
INSERT INTO images (owner_id, content_type, data)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateImageParams struct {
	OwnerID     int64
	ContentType string
	Data        []byte
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createImage, arg.OwnerID, arg.ContentType, arg.Data)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getImage = `-- name: GetImage :one
SELECT content_type, data, tg_file_id FROM images WHERE id = $1
`

type GetImageRow struct {
	ContentType string
	Data        []byte
	TgFileID    *string
}

func (q *Queries) GetImage(ctx context.Context, id uuid.UUID) (GetImageRow, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i GetImageRow
	err := row.Scan(&i.ContentType, &i.Data, &i.TgFileID)
	return i, err
}

const getImageOwner = `-- name: GetImageOwner :one
SELECT owner_id FROM images WHERE id = $1
`

func (q *Queries) GetImageOwner(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getImageOwner, id)
	var owner_id int64
	err := row.Scan(&owner_id)
	return owner_id, err
}

const setImageFileID = `-- name: SetImageFileID :exec
UPDATE images SET tg_file_id = $2 WHERE id = $1
`

type SetImageFileIDParams struct {
	ID       uuid.UUID
	TgFileID *string
}

func (q *Queries) SetImageFileID(ctx context.Context, arg SetImageFileIDParams) error {
	_, err := q.db.Exec(ctx, setImageFileID, arg.ID, arg.TgFileID)
	return err
}
