// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const creatorBalances = `-- name: CreatorBalances :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE account = 'creator_pending'), 0)::BIGINT   AS pending,
    COALESCE(SUM(amount) FILTER (WHERE account = 'creator_available'), 0)::BIGINT AS available,
    COALESCE(SUM(amount) FILTER (WHERE account = 'creator_payout'), 0)::BIGINT    AS paid_out
FROM ledger_entries
WHERE creator_id = $1 AND currency = $2
`

type CreatorBalancesParams struct {
	CreatorID *int64
	Currency  string
}

type CreatorBalancesRow struct {
	Pending   int64
	Available int64
	PaidOut   int64
}

func (q *Queries) CreatorBalances(ctx context.Context, arg CreatorBalancesParams) (CreatorBalancesRow, error) {
	row := q.db.QueryRow(ctx, creatorBalances, arg.CreatorID, arg.Currency)
	var i CreatorBalancesRow
	err := row.Scan(&i.Pending, &i.Available, &i.PaidOut)
	return i, err
}

const holdReleased = `-- name: HoldReleased :one
SELECT EXISTS (
    SELECT 1 FROM ledger_entries WHERE payment_id = $1 AND kind = 'hold_release'
)
`

func (q *Queries) HoldReleased(ctx context.Context, paymentID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, holdReleased, paymentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (account, creator_id, amount, currency, payment_id, payout_id, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLedgerEntryParams struct {
	Account   string
	CreatorID *int64
	Amount    int64
	Currency  string
	PaymentID *uuid.UUID
	PayoutID  *int64
	Kind      string
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.Account,
		arg.CreatorID,
		arg.Amount,
		arg.Currency,
		arg.PaymentID,
		arg.PayoutID,
		arg.Kind,
	)
	return err
}

const lockCreatorLedger = `-- name: LockCreatorLedger :exec
SELECT pg_advisory_xact_lock(hashtext('ledger:' || $1::BIGINT))
`

// Сериализует операции с балансом одного автора (вывод, освобождение холда).
func (q *Queries) LockCreatorLedger(ctx context.Context, creatorID int64) error {
	_, err := q.db.Exec(ctx, lockCreatorLedger, creatorID)
	return err
}
