// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type Channel struct {
	ID          int64
	OwnerID     int64
	ChatID      int64
	ChatType    string
	Title       string
	Username    *string
	Description string
	BotIsAdmin  bool
	InviteLink  *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BotIssue    string
	DeletedAt   *time.Time
}

type Image struct {
	ID          uuid.UUID
	OwnerID     int64
	ContentType string
	Data        []byte
	CreatedAt   time.Time
	TgFileID    *string
}

type LedgerEntry struct {
	ID        int64
	Account   string
	CreatorID *int64
	Amount    int64
	Currency  string
	PaymentID *uuid.UUID
	PayoutID  *int64
	Kind      string
	CreatedAt time.Time
}

type Payment struct {
	ID                uuid.UUID
	UserID            int64
	CreatorID         int64
	ChannelID         int64
	PlanID            int64
	Amount            int64
	Fee               int64
	Net               int64
	Currency          string
	Method            string
	Provider          string
	ProviderPaymentID *string
	PaymentUrl        *string
	Status            string
	CreatedAt         time.Time
	PaidAt            *time.Time
	UpdatedAt         time.Time
}

type Payout struct {
	ID          int64
	CreatorID   int64
	Amount      int64
	Currency    string
	Method      string
	Destination string
	Status      string
	Comment     string
	CreatedAt   time.Time
	ProcessedAt *time.Time
}

type Plan struct {
	ID          int64
	ChannelID   int64
	Title       string
	Description string
	Price       int64
	Currency    string
	PeriodDays  int32
	IsActive    bool
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ProductID   int64
}

type Product struct {
	ID             int64
	ChannelID      int64
	Title          string
	Description    string
	ButtonText     string
	ImageID        *uuid.UUID
	PaymentMethods []string
	IsActive       bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type Subscription struct {
	ID        int64
	ChannelID int64
	UserID    int64
	PlanID    int64
	Status    string
	StartedAt time.Time
	ExpiresAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID            int64
	Username      *string
	FirstName     string
	LastName      string
	PhotoUrl      *string
	LanguageCode  *string
	CommissionBps *int32
	IsBlocked     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
