// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, user_id, creator_id, channel_id, plan_id, amount, fee, net, currency, method, provider, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'pending')
RETURNING id, user_id, creator_id, channel_id, plan_id, amount, fee, net, currency, method, provider, provider_payment_id, payment_url, status, created_at, paid_at, updated_at
`

type CreatePaymentParams struct {
	ID        uuid.UUID
	UserID    int64
	CreatorID int64
	ChannelID int64
	PlanID    int64
	Amount    int64
	Fee       int64
	Net       int64
	Currency  string
	Method    string
	Provider  string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.UserID,
		arg.CreatorID,
		arg.ChannelID,
		arg.PlanID,
		arg.Amount,
		arg.Fee,
		arg.Net,
		arg.Currency,
		arg.Method,
		arg.Provider,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatorID,
		&i.ChannelID,
		&i.PlanID,
		&i.Amount,
		&i.Fee,
		&i.Net,
		&i.Currency,
		&i.Method,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, user_id, creator_id, channel_id, plan_id, amount, fee, net, currency, method, provider, provider_payment_id, payment_url, status, created_at, paid_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatorID,
		&i.ChannelID,
		&i.PlanID,
		&i.Amount,
		&i.Fee,
		&i.Net,
		&i.Currency,
		&i.Method,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentForUpdate = `-- name: GetPaymentForUpdate :one
SELECT id, user_id, creator_id, channel_id, plan_id, amount, fee, net, currency, method, provider, provider_payment_id, payment_url, status, created_at, paid_at, updated_at FROM payments WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetPaymentForUpdate(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentForUpdate, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatorID,
		&i.ChannelID,
		&i.PlanID,
		&i.Amount,
		&i.Fee,
		&i.Net,
		&i.Currency,
		&i.Method,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :exec
UPDATE payments SET status = 'failed', updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkPaymentFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentFailed, id)
	return err
}

const markPaymentSucceeded = `-- name: MarkPaymentSucceeded :one
UPDATE payments SET status = 'succeeded', paid_at = now(), updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, creator_id, channel_id, plan_id, amount, fee, net, currency, method, provider, provider_payment_id, payment_url, status, created_at, paid_at, updated_at
`

// Переход только из pending — повторный вебхук ничего не изменит.
func (q *Queries) MarkPaymentSucceeded(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentSucceeded, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatorID,
		&i.ChannelID,
		&i.PlanID,
		&i.Amount,
		&i.Fee,
		&i.Net,
		&i.Currency,
		&i.Method,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.PaymentUrl,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPaymentProviderData = `-- name: SetPaymentProviderData :exec
UPDATE payments SET provider_payment_id = $2, payment_url = $3, updated_at = now() WHERE id = $1
`

type SetPaymentProviderDataParams struct {
	ID                uuid.UUID
	ProviderPaymentID *string
	PaymentUrl        *string
}

func (q *Queries) SetPaymentProviderData(ctx context.Context, arg SetPaymentProviderDataParams) error {
	_, err := q.db.Exec(ctx, setPaymentProviderData, arg.ID, arg.ProviderPaymentID, arg.PaymentUrl)
	return err
}
