// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payouts.sql

package store

import (
	"context"
)

const createPayout = `-- name: CreatePayout :one
INSERT INTO payouts (creator_id, amount, currency, method, destination, status)
VALUES ($1, $2, $3, $4, $5, 'requested')
RETURNING id, creator_id, amount, currency, method, destination, status, comment, created_at, processed_at
`

type CreatePayoutParams struct {
	CreatorID   int64
	Amount      int64
	Currency    string
	Method      string
	Destination string
}

func (q *Queries) CreatePayout(ctx context.Context, arg CreatePayoutParams) (Payout, error) {
	row := q.db.QueryRow(ctx, createPayout,
		arg.CreatorID,
		arg.Amount,
		arg.Currency,
		arg.Method,
		arg.Destination,
	)
	var i Payout
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Amount,
		&i.Currency,
		&i.Method,
		&i.Destination,
		&i.Status,
		&i.Comment,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const listPayoutsByCreator = `-- name: ListPayoutsByCreator :many
SELECT id, creator_id, amount, currency, method, destination, status, comment, created_at, processed_at FROM payouts WHERE creator_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListPayoutsByCreatorParams struct {
	CreatorID int64
	Limit     int32
}

func (q *Queries) ListPayoutsByCreator(ctx context.Context, arg ListPayoutsByCreatorParams) ([]Payout, error) {
	rows, err := q.db.Query(ctx, listPayoutsByCreator, arg.CreatorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payout
	for rows.Next() {
		var i Payout
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Amount,
			&i.Currency,
			&i.Method,
			&i.Destination,
			&i.Status,
			&i.Comment,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
