// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package store

import (
	"context"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (channel_id, product_id, title, price, currency, period_days, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, channel_id, title, description, price, currency, period_days, is_active, sort_order, created_at, updated_at, product_id
`

type CreatePlanParams struct {
	ChannelID  int64
	ProductID  int64
	Title      string
	Price      int64
	Currency   string
	PeriodDays int32
	SortOrder  int32
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ChannelID,
		arg.ProductID,
		arg.Title,
		arg.Price,
		arg.Currency,
		arg.PeriodDays,
		arg.SortOrder,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.PeriodDays,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductID,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, channel_id, title, description, price, currency, period_days, is_active, sort_order, created_at, updated_at, product_id FROM plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.PeriodDays,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductID,
	)
	return i, err
}

const listActivePlansByProduct = `-- name: ListActivePlansByProduct :many
SELECT id, channel_id, title, description, price, currency, period_days, is_active, sort_order, created_at, updated_at, product_id FROM plans WHERE product_id = $1 AND is_active ORDER BY sort_order, period_days = 0, period_days, price
`

func (q *Queries) ListActivePlansByProduct(ctx context.Context, productID int64) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActivePlansByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.PeriodDays,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByProduct = `-- name: ListPlansByProduct :many
SELECT id, channel_id, title, description, price, currency, period_days, is_active, sort_order, created_at, updated_at, product_id FROM plans WHERE product_id = $1 ORDER BY sort_order, period_days = 0, period_days, price
`

func (q *Queries) ListPlansByProduct(ctx context.Context, productID int64) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlansByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.PeriodDays,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET
    title       = $2,
    price       = $3,
    period_days = $4,
    is_active   = $5,
    updated_at  = now()
WHERE id = $1
RETURNING id, channel_id, title, description, price, currency, period_days, is_active, sort_order, created_at, updated_at, product_id
`

type UpdatePlanParams struct {
	ID         int64
	Title      string
	Price      int64
	PeriodDays int32
	IsActive   bool
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Title,
		arg.Price,
		arg.PeriodDays,
		arg.IsActive,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.PeriodDays,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductID,
	)
	return i, err
}
