// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countProductSubscribers = `-- name: CountProductSubscribers :one
SELECT count(*)::BIGINT
FROM subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE p.product_id = $1 AND s.status = 'active'
`

func (q *Queries) CountProductSubscribers(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProductSubscribers, productID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (channel_id, title, description, button_text, image_id, payment_methods)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, channel_id, title, description, button_text, image_id, payment_methods, is_active, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	ChannelID      int64
	Title          string
	Description    string
	ButtonText     string
	ImageID        *uuid.UUID
	PaymentMethods []string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.ButtonText,
		arg.ImageID,
		arg.PaymentMethods,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.ButtonText,
		&i.ImageID,
		&i.PaymentMethods,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, channel_id, title, description, button_text, image_id, payment_methods, is_active, created_at, updated_at, deleted_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.ButtonText,
		&i.ImageID,
		&i.PaymentMethods,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProductsByChannel = `-- name: ListProductsByChannel :many
SELECT id, channel_id, title, description, button_text, image_id, payment_methods, is_active, created_at, updated_at, deleted_at FROM products WHERE channel_id = $1 AND deleted_at IS NULL ORDER BY created_at, id
`

func (q *Queries) ListProductsByChannel(ctx context.Context, channelID int64) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.ButtonText,
			&i.ImageID,
			&i.PaymentMethods,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = now(), is_active = FALSE WHERE id = $1
`

// Подписка пропадает из приложения и со страницы оплаты. Кто уже оплатил, сохраняет доступ до конца срока.
func (q *Queries) SoftDeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    title           = $2,
    description     = $3,
    button_text     = $4,
    image_id        = $5,
    payment_methods = $6,
    is_active       = $7,
    updated_at      = now()
WHERE id = $1
RETURNING id, channel_id, title, description, button_text, image_id, payment_methods, is_active, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID             int64
	Title          string
	Description    string
	ButtonText     string
	ImageID        *uuid.UUID
	PaymentMethods []string
	IsActive       bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ButtonText,
		arg.ImageID,
		arg.PaymentMethods,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.ButtonText,
		&i.ImageID,
		&i.PaymentMethods,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
