// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const creatorDailyRevenue = `-- name: CreatorDailyRevenue :many
SELECT
    date_trunc('day', paid_at AT TIME ZONE $1::TEXT)::DATE AS day,
    SUM(net)::BIGINT AS net,
    COUNT(*)::BIGINT AS payments
FROM payments
WHERE creator_id = $2 AND status = 'succeeded' AND paid_at >= $3::TIMESTAMPTZ
  AND ($4::BIGINT IS NULL OR channel_id = $4::BIGINT)
GROUP BY 1
ORDER BY 1
`

type CreatorDailyRevenueParams struct {
	Tz        string
	CreatorID int64
	Since     time.Time
	ChannelID *int64
}

type CreatorDailyRevenueRow struct {
	Day      time.Time
	Net      int64
	Payments int64
}

func (q *Queries) CreatorDailyRevenue(ctx context.Context, arg CreatorDailyRevenueParams) ([]CreatorDailyRevenueRow, error) {
	rows, err := q.db.Query(ctx, creatorDailyRevenue,
		arg.Tz,
		arg.CreatorID,
		arg.Since,
		arg.ChannelID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreatorDailyRevenueRow
	for rows.Next() {
		var i CreatorDailyRevenueRow
		if err := rows.Scan(&i.Day, &i.Net, &i.Payments); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const creatorDayPayments = `-- name: CreatorDayPayments :many
SELECT p.id, p.paid_at, p.amount, p.net, p.method,
       c.title AS channel_title, pl.title AS plan_title,
       COALESCE(NULLIF(u.first_name, ''), u.username, 'Подписчик')::TEXT AS payer_name
FROM payments p
JOIN channels c ON c.id = p.channel_id
JOIN plans pl ON pl.id = p.plan_id
JOIN users u ON u.id = p.user_id
WHERE p.creator_id = $1 AND p.status = 'succeeded'
  AND ($2::TIMESTAMPTZ IS NULL OR p.paid_at >= $2::TIMESTAMPTZ)
  AND ($3::TIMESTAMPTZ IS NULL OR p.paid_at < $3::TIMESTAMPTZ)
  AND ($4::BIGINT IS NULL OR p.channel_id = $4::BIGINT)
ORDER BY p.paid_at DESC
LIMIT $5
`

type CreatorDayPaymentsParams struct {
	CreatorID int64
	DayStart  *time.Time
	DayEnd    *time.Time
	ChannelID *int64
	MaxRows   int32
}

type CreatorDayPaymentsRow struct {
	ID           uuid.UUID
	PaidAt       *time.Time
	Amount       int64
	Net          int64
	Method       string
	ChannelTitle string
	PlanTitle    string
	PayerName    string
}

func (q *Queries) CreatorDayPayments(ctx context.Context, arg CreatorDayPaymentsParams) ([]CreatorDayPaymentsRow, error) {
	rows, err := q.db.Query(ctx, creatorDayPayments,
		arg.CreatorID,
		arg.DayStart,
		arg.DayEnd,
		arg.ChannelID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreatorDayPaymentsRow
	for rows.Next() {
		var i CreatorDayPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaidAt,
			&i.Amount,
			&i.Net,
			&i.Method,
			&i.ChannelTitle,
			&i.PlanTitle,
			&i.PayerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const creatorStatsSummary = `-- name: CreatorStatsSummary :one
SELECT
    COALESCE(SUM(net) FILTER (WHERE status = 'succeeded'), 0)::BIGINT AS net_revenue,
    COALESCE(SUM(amount) FILTER (WHERE status = 'succeeded'), 0)::BIGINT AS gross_revenue,
    COUNT(*) FILTER (WHERE status = 'succeeded')::BIGINT AS payments_count,
    COUNT(DISTINCT user_id) FILTER (WHERE status = 'succeeded')::BIGINT AS paying_users
FROM payments
WHERE creator_id = $1 AND created_at >= $2::TIMESTAMPTZ
  AND ($3::BIGINT IS NULL OR channel_id = $3::BIGINT)
`

type CreatorStatsSummaryParams struct {
	CreatorID int64
	Since     time.Time
	ChannelID *int64
}

type CreatorStatsSummaryRow struct {
	NetRevenue    int64
	GrossRevenue  int64
	PaymentsCount int64
	PayingUsers   int64
}

func (q *Queries) CreatorStatsSummary(ctx context.Context, arg CreatorStatsSummaryParams) (CreatorStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, creatorStatsSummary, arg.CreatorID, arg.Since, arg.ChannelID)
	var i CreatorStatsSummaryRow
	err := row.Scan(
		&i.NetRevenue,
		&i.GrossRevenue,
		&i.PaymentsCount,
		&i.PayingUsers,
	)
	return i, err
}

const creatorSubscriberCounts = `-- name: CreatorSubscriberCounts :one
SELECT
    COUNT(*) FILTER (WHERE s.status = 'active')::BIGINT AS active,
    COUNT(*) FILTER (WHERE s.status = 'active' AND s.started_at >= $1::TIMESTAMPTZ)::BIGINT AS new_active,
    COUNT(*) FILTER (WHERE s.status = 'expired' AND s.updated_at >= $1::TIMESTAMPTZ)::BIGINT AS churned
FROM subscriptions s
JOIN channels c ON c.id = s.channel_id
WHERE c.owner_id = $2
  AND ($3::BIGINT IS NULL OR c.id = $3::BIGINT)
`

type CreatorSubscriberCountsParams struct {
	Since     time.Time
	CreatorID int64
	ChannelID *int64
}

type CreatorSubscriberCountsRow struct {
	Active    int64
	NewActive int64
	Churned   int64
}

func (q *Queries) CreatorSubscriberCounts(ctx context.Context, arg CreatorSubscriberCountsParams) (CreatorSubscriberCountsRow, error) {
	row := q.db.QueryRow(ctx, creatorSubscriberCounts, arg.Since, arg.CreatorID, arg.ChannelID)
	var i CreatorSubscriberCountsRow
	err := row.Scan(&i.Active, &i.NewActive, &i.Churned)
	return i, err
}
