// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package store

import (
	"context"
	"time"
)

const activateSubscription = `-- name: ActivateSubscription :one
INSERT INTO subscriptions (channel_id, user_id, plan_id, status, started_at, expires_at)
VALUES (
    $1, $2, $3, 'active', now(),
    CASE WHEN $4::INT IS NULL THEN NULL
         ELSE now() + make_interval(days => $4::INT) END
)
ON CONFLICT (channel_id, user_id) DO UPDATE SET
    plan_id    = EXCLUDED.plan_id,
    status     = 'active',
    started_at = CASE WHEN subscriptions.status = 'active' THEN subscriptions.started_at ELSE now() END,
    expires_at = CASE
        WHEN $4::INT IS NULL THEN NULL
        WHEN subscriptions.status = 'active' AND subscriptions.expires_at IS NULL THEN NULL
        WHEN subscriptions.status = 'active' AND subscriptions.expires_at > now()
            THEN subscriptions.expires_at + make_interval(days => $4::INT)
        ELSE now() + make_interval(days => $4::INT)
    END,
    updated_at = now()
RETURNING id, channel_id, user_id, plan_id, status, started_at, expires_at, created_at, updated_at
`

type ActivateSubscriptionParams struct {
	ChannelID  int64
	UserID     int64
	PlanID     int64
	PeriodDays *int32
}

// Создаёт подписку или продлевает существующую.
// Если подписка ещё активна — время добавляется к текущему expires_at, иначе считается от now().
// sqlc.narg('period_days') = NULL означает бессрочный доступ.
func (q *Queries) ActivateSubscription(ctx context.Context, arg ActivateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, activateSubscription,
		arg.ChannelID,
		arg.UserID,
		arg.PlanID,
		arg.PeriodDays,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveSubscribers = `-- name: CountActiveSubscribers :one
SELECT count(*)::BIGINT FROM subscriptions WHERE channel_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveSubscribers(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSubscribers, channelID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const expireDueSubscriptions = `-- name: ExpireDueSubscriptions :many
UPDATE subscriptions SET status = 'expired', updated_at = now()
WHERE id IN (
    SELECT id FROM subscriptions
    WHERE status = 'active' AND expires_at IS NOT NULL AND expires_at <= now()
    ORDER BY expires_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, channel_id, user_id, plan_id, status, started_at, expires_at, created_at, updated_at
`

// Помечает истёкшие подписки и возвращает их, чтобы воркер удалил людей из канала.
func (q *Queries) ExpireDueSubscriptions(ctx context.Context, limit int32) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, expireDueSubscriptions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, channel_id, user_id, plan_id, status, started_at, expires_at, created_at, updated_at FROM subscriptions WHERE channel_id = $1 AND user_id = $2
`

type GetSubscriptionParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.ChannelID, arg.UserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, channel_id, user_id, plan_id, status, started_at, expires_at, created_at, updated_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveSubscription = `-- name: HasActiveSubscription :one
SELECT EXISTS (
    SELECT 1 FROM subscriptions
    WHERE channel_id = $1 AND user_id = $2 AND status = 'active'
      AND (expires_at IS NULL OR expires_at > now())
)
`

type HasActiveSubscriptionParams struct {
	ChannelID int64
	UserID    int64
}

func (q *Queries) HasActiveSubscription(ctx context.Context, arg HasActiveSubscriptionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSubscription, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSubscriptionsByUser = `-- name: ListSubscriptionsByUser :many
SELECT
    s.id, s.channel_id, s.user_id, s.plan_id, s.status, s.started_at, s.expires_at, s.created_at, s.updated_at,
    c.title    AS channel_title,
    c.username AS channel_username,
    c.invite_link AS channel_invite_link,
    p.title    AS plan_title,
    p.price    AS plan_price,
    p.currency AS plan_currency
FROM subscriptions s
JOIN channels c ON c.id = s.channel_id
JOIN plans p ON p.id = s.plan_id
WHERE s.user_id = $1
ORDER BY (s.status = 'active') DESC, s.expires_at DESC NULLS FIRST
`

type ListSubscriptionsByUserRow struct {
	ID                int64
	ChannelID         int64
	UserID            int64
	PlanID            int64
	Status            string
	StartedAt         time.Time
	ExpiresAt         *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ChannelTitle      string
	ChannelUsername   *string
	ChannelInviteLink *string
	PlanTitle         string
	PlanPrice         int64
	PlanCurrency      string
}

func (q *Queries) ListSubscriptionsByUser(ctx context.Context, userID int64) ([]ListSubscriptionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsByUserRow
	for rows.Next() {
		var i ListSubscriptionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ChannelTitle,
			&i.ChannelUsername,
			&i.ChannelInviteLink,
			&i.PlanTitle,
			&i.PlanPrice,
			&i.PlanCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
