// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const ensureUser = `-- name: EnsureUser :exec
INSERT INTO users (id, username, first_name, last_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type EnsureUserParams struct {
	ID        int64
	Username  *string
	FirstName string
	LastName  string
}

// Используется ботом, когда о пользователе известно только id и имя.
func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) error {
	_, err := q.db.Exec(ctx, ensureUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, first_name, last_name, photo_url, language_code, commission_bps, is_blocked, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.PhotoUrl,
		&i.LanguageCode,
		&i.CommissionBps,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, username, first_name, last_name, photo_url, language_code)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    username      = EXCLUDED.username,
    first_name    = EXCLUDED.first_name,
    last_name     = EXCLUDED.last_name,
    photo_url     = COALESCE(EXCLUDED.photo_url, users.photo_url),
    language_code = EXCLUDED.language_code,
    updated_at    = now()
RETURNING id, username, first_name, last_name, photo_url, language_code, commission_bps, is_blocked, created_at, updated_at
`

type UpsertUserParams struct {
	ID           int64
	Username     *string
	FirstName    string
	LastName     string
	PhotoUrl     *string
	LanguageCode *string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.PhotoUrl,
		arg.LanguageCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.PhotoUrl,
		&i.LanguageCode,
		&i.CommissionBps,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
