/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь, баланс и настройки платформы */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Каналы, где текущий пользователь — владелец */
        get: operations["listChannels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ссылка, по которой автор добавляет бота админом в свой канал */
        get: operations["getConnectLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/channels/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        /** Канал с подписками (только для владельца) */
        get: operations["getChannel"];
        put?: never;
        post?: never;
        /** Удалить канал из Pitly. Продажи останавливаются, бот выходит из канала */
        delete: operations["deleteChannel"];
        options?: never;
        head?: never;
        /** Обновить описание канала на странице оплаты */
        patch: operations["updateChannel"];
        trace?: never;
    };
    "/channels/{channelId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать подписку в канале вместе с периодами */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        /** Подписка с периодами (только для владельца) */
        get: operations["getProduct"];
        /** Изменить название, описание, оформление и способы оплаты */
        put: operations["updateProduct"];
        post?: never;
        /** Удалить подписку. Кто уже оплатил, сохраняет доступ до конца срока */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить период подписки */
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/share": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подготовить пост подписки, который автор отправит в чат или канал */
        post: operations["shareProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}/offer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        /** Страница оплаты конкретной подписки для подписчика */
        get: operations["getProductOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Изменить период */
        put: operations["updatePlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{channelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        /** Страница оплаты канала для подписчика — первая подписка, которая в продаже */
        get: operations["getOffer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать платёж и получить ссылку на оплату */
        post: operations["createCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        /** Статус платежа (подписчик опрашивает после возврата со страницы оплаты) */
        get: operations["getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Подписки текущего пользователя как подписчика */
        get: operations["listMySubscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статистика автора */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Успешные оплаты автора — за один день или последние */
        get: operations["listDayPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История выводов */
        get: operations["listPayouts"];
        put?: never;
        /** Запросить вывод доступного баланса */
        post: operations["requestPayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Машиночитаемый код (not_found, forbidden, validation, ...) */
            code: string;
            message: string;
        };
        User: {
            /** Format: int64 */
            id: number;
            username?: string;
            firstName: string;
            lastName: string;
            photoUrl?: string;
        };
        Balance: {
            /** @example RUB */
            currency: string;
            /**
             * Format: int64
             * @description В холде, станет доступно после окончания холда
             */
            pending: number;
            /**
             * Format: int64
             * @description Можно вывести
             */
            available: number;
            /**
             * Format: int64
             * @description Всего выведено
             */
            paidOut: number;
        };
        Me: {
            user: components["schemas"]["User"];
            balance: components["schemas"]["Balance"];
            /** @description Комиссия платформы для этого автора, 2000 = 20% */
            commissionBps: number;
            /** Format: int64 */
            minPayout: number;
            holdHours: number;
            payoutMethods: components["schemas"]["PayoutMethod"][];
        };
        Channel: {
            /**
             * @description Что не так с ботом в канале. removed — бота убрали, no_rights — не хватает прав
             * @enum {string}
             */
            botIssue: "none" | "removed" | "no_rights";
            /**
             * Format: date-time
             * @description Когда бота последний раз добавили админом в этот канал
             */
            connectedAt: string;
            /** Format: int64 */
            id: number;
            title: string;
            username?: string;
            /** @enum {string} */
            chatType: "channel" | "supergroup" | "group";
            description: string;
            /** @description false — бота удалили из админов, продажи остановлены */
            botIsAdmin: boolean;
            /** Format: int64 */
            activeSubscribers: number;
            /** @description Ссылка на страницу оплаты, которой автор делится с аудиторией */
            offerUrl: string;
        };
        ChannelDetail: {
            channel: components["schemas"]["Channel"];
            products: components["schemas"]["Product"][];
        };
        ChannelUpdate: {
            description: string;
        };
        ConnectLink: {
            url: string;
            botUsername: string;
        };
        Product: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            channelId: number;
            channelTitle: string;
            title: string;
            description: string;
            /** @description Надпись на кнопке под постом */
            buttonText: string;
            /** Format: uuid */
            imageId?: string;
            imageUrl?: string;
            /** @description Пустой список — доступны все способы */
            paymentMethods: components["schemas"]["PaymentMethod"][];
            isActive: boolean;
            /** Format: int64 */
            activeSubscribers: number;
            /** @description Ссылка на страницу оплаты этой подписки */
            url: string;
            plans: components["schemas"]["Plan"][];
        };
        PreparedShare: {
            /** @description Идентификатор для WebApp.shareMessage */
            preparedMessageId: string;
        };
        ProductInput: {
            title: string;
            description?: string;
            buttonText?: string;
            /**
             * Format: uuid
             * @description Не передан — картинки нет
             */
            imageId?: string;
            paymentMethods?: components["schemas"]["PaymentMethod"][];
        };
        ProductCreate: components["schemas"]["ProductInput"] & {
            /** @description Периоды, с которыми создаётся подписка. Сроки не повторяются */
            plans: components["schemas"]["PlanInput"][];
        };
        ProductUpdate: components["schemas"]["ProductInput"] & {
            isActive: boolean;
        };
        Plan: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            channelId: number;
            /** Format: int64 */
            productId: number;
            /** @description Название периода, собирается из срока */
            title: string;
            /** Format: int64 */
            price: number;
            currency: string;
            /** @description 0 — бессрочный доступ */
            periodDays: number;
            isActive: boolean;
        };
        PlanInput: {
            /** Format: int64 */
            price: number;
            periodDays: number;
        };
        PlanUpdate: components["schemas"]["PlanInput"] & {
            isActive: boolean;
        };
        Offer: {
            /** @description true — страницу открыл владелец канала, купить у себя нельзя */
            own: boolean;
            /** Format: int64 */
            channelId: number;
            /**
             * Format: int64
             * @description Отсутствует, если у канала нет подписок в продаже
             */
            productId?: number;
            productTitle?: string;
            buttonText: string;
            imageUrl?: string;
            /** @description Название канала */
            title: string;
            username?: string;
            description: string;
            /** @description false — канал временно не принимает оплату */
            available: boolean;
            plans: components["schemas"]["Plan"][];
            paymentMethods: components["schemas"]["PaymentMethod"][];
            subscription?: components["schemas"]["MySubscription"];
        };
        /** @enum {string} */
        PaymentMethod: "card" | "sbp";
        /** @enum {string} */
        PayoutMethod: "card" | "sbp" | "usdt_ton";
        CheckoutRequest: {
            /** Format: int64 */
            planId: number;
            method: components["schemas"]["PaymentMethod"];
        };
        Checkout: {
            /** Format: uuid */
            paymentId: string;
            paymentUrl: string;
        };
        PaymentStatus: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "pending" | "succeeded" | "failed" | "refunded";
            /** Format: int64 */
            amount: number;
            currency: string;
            /** Format: int64 */
            channelId: number;
            channelTitle: string;
            /** @description Появляется после успешной оплаты */
            inviteLink?: string;
        };
        MySubscription: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            channelId: number;
            channelTitle: string;
            channelUsername?: string;
            planTitle: string;
            /** @enum {string} */
            status: "active" | "expired" | "canceled";
            /** Format: date-time */
            startedAt: string;
            /**
             * Format: date-time
             * @description Отсутствует у бессрочного доступа
             */
            expiresAt?: string;
            inviteLink?: string;
        };
        Stats: {
            days: number;
            currency: string;
            /**
             * Format: int64
             * @description Доход автора после комиссии
             */
            netRevenue: number;
            /**
             * Format: int64
             * @description Сколько заплатили подписчики
             */
            grossRevenue: number;
            /** Format: int64 */
            paymentsCount: number;
            /** Format: int64 */
            payingUsers: number;
            /** Format: int64 */
            activeSubscribers: number;
            /** Format: int64 */
            newSubscribers: number;
            /** Format: int64 */
            churnedSubscribers: number;
            daily: components["schemas"]["DailyPoint"][];
        };
        DailyPoint: {
            /** Format: date */
            date: string;
            /** Format: int64 */
            net: number;
            /** Format: int64 */
            payments: number;
        };
        DayPayment: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            paidAt: string;
            /** Format: int64 */
            amount: number;
            /** Format: int64 */
            net: number;
            method: components["schemas"]["PaymentMethod"];
            channelTitle: string;
            planTitle: string;
            payerName: string;
        };
        Payout: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            amount: number;
            currency: string;
            method: components["schemas"]["PayoutMethod"];
            /** @description Замаскированные реквизиты */
            destination: string;
            /** @enum {string} */
            status: "requested" | "processing" | "paid" | "rejected";
            comment?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            processedAt?: string;
        };
        PayoutRequest: {
            /** Format: int64 */
            amount: number;
            method: components["schemas"]["PayoutMethod"];
            destination: string;
        };
    };
    responses: {
        /** @description Ошибка */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ProductId: number;
        ChannelId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getConnectLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectLink"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Channel"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    shareProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreparedShare"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProductOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updatePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channelId: components["parameters"]["ChannelId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checkout"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMySubscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySubscription"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStats: {
        parameters: {
            query?: {
                days?: number;
                /** @description Только один канал автора */
                channelId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDayPayments: {
        parameters: {
            query?: {
                /** @description День. Без него отдаются последние оплаты */
                date?: string;
                /** @description Только один канал автора */
                channelId?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayPayment"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listPayouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payout"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    requestPayout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayoutRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payout"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
